Allowing 'ssl' to be absent in 'email' alerts
Fixing this
```Traceback (most recent call last):
  File "monitor.py", line 477, in <module>
    main()
  File "monitor.py", line 349, in main
    m = load_alerters(m, config)
  File "monitor.py", line 211, in load_alerters
    new_alerter = Alerters.mail.EMailAlerter(config_options)
  File "/home/tschaller/simplemonitor/Alerters/mail.py", line 56, in __init__
    allow_empty=True
  File "/home/tschaller/simplemonitor/Alerters/alerter.py", line 145, in get_config_option
    return get_config_option(config_options, key, **kwargs)
  File "/home/tschaller/simplemonitor/util.py", line 73, in get_config_option
    raise exception('config option {0} needs to be one of {1}'.format(key, allowed_values))
util.AlerterConfigurationError: config option ssl needs to be one of ['starttls', 'yes']
```